name: publish to nuget
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build solution and generate NuGet package
        run: |
          cd XeonApps.Extensions.Logging.WithProperty
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}} 
        run: >
          dotnet nuget push ./XeonApps.Extensions.Logging.WithProperty/out/*.nupkg
          --skip-duplicate --no-symbols true
